# Generated by Django 4.2.5 on 2024-06-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scbot_api', '0002_project_communications_project_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Communications',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Files',
        ),
    ]
