# Generated by Django 4.2.5 on 2024-06-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scbot_api', '0004_alter_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
