# Generated by Django 4.2.5 on 2024-06-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scbot_api', '0005_remove_file_url_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='sender',
            field=models.CharField(default='SCBOT', max_length=255),
        ),
    ]
